spring.application.name: CamundaWebApplication

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/camunda
    username: camunda
    password: camunda

camunda:
  bpm:
    job-execution.deployment-aware: true

zuul:
  endpoints.routes.enabled: false
  routes:
    async_deployment:
      path: /camunda-bpm-engine/**
      url: http://localhost:8090/forms